language: ruby
rvm:
  - 2.3.1

env:
  - DB=pgsql

services:
  - postgresql

test:
  adapter: postgresql
  database: travis_ci_test

before_script:
- psql -c 'create database travis_ci_test;' -U postgres

script:
  - mkdir -p spec && bundle exec rspec spec
