language: ruby
rvm:
  - 2.3.1

env:
  - DB=pgsql

services:
  - postgresql

test:
  adapter: postgresql
  database: travis_ci_test
  
before_script:
  - cp config/database.yml.travis config/database.yml

script:
  - mkdir -p spec && bundle exec rspec spec
